#! /bin/sh

#set -e

DONT=""
INTYPE="cert"
NAME="*"
PORT="443"
PROGNAME="${0##*/}"
TTL="3600"
VERBOSITY=0

###
### Functions
###

processCert() {
	local cert="${1}"

	verbose "Processing ${INTYPE} '${cert}'..." 1

	cmd="x509"
	if [ x"${INTYPE}" = x"csr" ]; then
		cmd="req"
	fi

	for name in $(<"${cert}" openssl ${cmd} -text -noout | grep DNS: | sed -e 's/DNS://g' -e 's/,/ /g'); do
		if [ x"${NAME}" != x"${name}" ] && [ x"${NAME}" != x"*" ]; then
			verbose "Skipping SAN '${name}'..." 2
			continue
		fi

		verbose "Creating TLSA record for SAN '${name}'..." 2
		short=$(echo ${name} | sed -e 's/\(.*\)\..*\..*/\1/')
		domain=${name##${short}.}
		if [ x"${short}" = x"${name}" ]; then
			short=""
			domain="${name}"
		else
			short=".${short}"
		fi
		rrset_name="_${PORT}._tcp${short}"
		keycmd="x509"
		if [ x"${INTYPE}" = x"csr" ]; then
			keycmd="req"
		fi

		nextKey="${cert%.*}.key.next"
		if [ -f "${nextKey}" ]; then
			verbose "Creating TLSA record for '${domain}' next key..." 2
			nextsha256=$(<"${nextKey}" openssl pkey -pubout -outform DER |  \
				openssl sha256 | awk '{print toupper($NF);}')
		fi
		sha256=$(<"${cert}" openssl ${keycmd} -noout -pubkey |    	\
				openssl pkey -pubin -pubout -outform DER 2>/dev/null | \
				openssl sha256 | awk '{print toupper($NF);}')

		updateRecord "${sha256}" "${domain}" "${nextsha256}"

	done
}

patchRecord() {
	local add_or_remove="${1}"
	local domain="${2}"
	local rrset_name="${3}"
	local rr_type="${4}"
	local value="${5}"

	verbose "Patching ${rr_type} record ${rr}.${domain} to ${add_or_remove} ${value}..." 4
	curl_out="$(${DONT} curl -s -X PATCH \
				-H "Content-Type: application/json"	\
				-H "Authorization: Bearer ${GANDI_ACCESS_TOKEN}"	\
				-d "{ \"${add_or_remove}_rrset_values\" : [\"${value}\"] }"	\
				https://api.gandi.net/v5/livedns/domains/${domain}/records/${rrset_name}/${rr_type})"
	if [ -n "${DONT}" ]; then
		echo "${curl_out}"
	fi
}

updateRecord() {
	local sha256="${1}"
	local domain="${2}"
	local nextsha256="${3}"

	# We want to avoid a false negative on a cached negative by the local
	# resolver, so we dig @ the auth.
	auth=$(dig +short "${domain}" "ns" | head -1)
	dig_out=$(dig ${auth+@${auth}} +short "${rrset_name}.${domain}" "tlsa")
	found=$(echo "${dig_out}" | sed -e 's/^. . . //' | tr '[a-z]' '[A-Z]' | tr -d ' ')
	for f_sum in ${found}; do
		if [ x"${f_sum}" = x"${sha256}" ]; then
			echo "TLSA record with SHA256 '${sha256}' already exists." >&2
			sha256="x"
		elif [ -n "${nextsha256}" ] && [ x"${f_sum}" = x"${nextsha256}" ]; then
			echo "TLSA record with next SHA256 '${nextsha256}' already exists." >&2
			nextsha256="x"
		else
			patchRecord "remove" "${domain}" "${rrset_name}" "TLSA" "${f_sym}"
		fi
	done

	if [ x"${sha256}" != x"x" ]; then
		patchRecord "add" "${domain}" "${rrset_name}" "TLSA" "3 1 1 ${sha256}"
	fi
	if [ x"${nextsha256}" != x"x" ]; then
		patchRecord "add" "${domain}" "${rrset_name}" "TLSA" "3 1 1 ${nextsha256}"
	fi
}

usage() {
	cat <<EOH
Usage: ${PROGNAME} [-dhv] [-i cert|csr] [-n name] [-p port] [-t ttl] certfile ...
	-d           don't do anything, just show what would be done
	-h           print this help and exit
	-i cert|csr  specify input type (default: cert)
	-n name      only add records for this name
	-p port      specify port (default: 443)
	-t ttl       specify the TTL (default: 3600)
	-v           be verbose
EOH
}

verbose() {
	local readonly msg="${1}"
	local level="${2:-1}"
	local i=0

	if [ ${level} -le ${VERBOSITY} ]; then
		while [ ${i} -lt ${level} ]; do
			printf "=" >&2
			i=$(( ${i} + 1 ))
		done
		echo "> ${msg}" >&2
	fi
}

###
### Main
###

while getopts 'dhi:n:p:t:v' opt; do
	case "${opt}" in
		d)
			DONT="echo"
		;;
		h\?)
			usage
			exit 0
			# NOTREACHED
		;;
		i)
			if [ "${OPTARG}" != "cert" -a "${OPTARG}" != "csr" ]; then
				echo "Invalid argument '${OPTARG}' for '-i'." >&2
				echo "Acceptable values: cert, csr" >&2
				exit 1
				# NOTREACHED
			fi
			INTYPE="${OPTARG}"
		;;
		n)
			NAME="${OPTARG}"
		;;
		p)
			PORT="${OPTARG}"
		;;
		t)
			TTL="${OPTARG}"
		;;
		v)
			VERBOSITY=$(( ${VERBOSITY} + 1 ))
		;;
		*)
			usage
			exit 1
			# NOTREACHED
		;;
	esac
done
shift $(($OPTIND - 1))

if [ $# -lt 1 ]; then
	usage
	exit 1
	# NOTREACHED
fi

if [ -z "${GANDI_ACCESS_TOKEN}" -a -z "${DONT}" ]; then
	echo "GANDI_ACCESS_TOKEN not set in the environment." >&2
	echo "Please generate an API key at https://admin.gandi.net/organizations/account/pat and" >&2
	echo "export GANDI_ACCESS_TOKEN=<your new API key>" >&2
	exit 1
fi

for cert in "$@"; do
	processCert "${cert}"
done
